name: Lint

permissions:
  contents: read

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
          cache: true

      - uses: golangci/golangci-lint-action@v6
        with:
          args: --issues-exit-code=0
          only-new-issues: true
