name: Release

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          cache: true

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
